// <auto-generated />
using System;
using EFCore.WebAPI.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Repo.Migrations
{
    [DbContext(typeof(ITContext))]
    [Migration("20220324233216_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore.WebAPI.Dominio.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FuncionarioId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("EFCore.WebAPI.Dominio.FuncSquad", b =>
                {
                    b.Property<int>("FuncionarioId");

                    b.Property<int>("SquadId");

                    b.HasKey("FuncionarioId", "SquadId");

                    b.HasIndex("SquadId");

                    b.ToTable("FuncionariosSquads");
                });

            modelBuilder.Entity("EFCore.WebAPI.Dominio.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("EFCore.WebAPI.Dominio.Gestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FuncionarioId");

                    b.Property<string>("NomeReal");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("EFCore.WebAPI.Dominio.Squad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("DtFim");

                    b.Property<DateTime>("DtInicio");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("EFCore.WebAPI.Dominio.Equipamento", b =>
                {
                    b.HasOne("EFCore.WebAPI.Dominio.Funcionario", "Funcionario")
                        .WithMany("Equipamentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCore.WebAPI.Dominio.FuncSquad", b =>
                {
                    b.HasOne("EFCore.WebAPI.Dominio.Funcionario", "Funcionario")
                        .WithMany("FuncionariosSquads")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EFCore.WebAPI.Dominio.Squad", "Squad")
                        .WithMany("FuncionariosSquads")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCore.WebAPI.Dominio.Gestor", b =>
                {
                    b.HasOne("EFCore.WebAPI.Dominio.Funcionario", "Funcionario")
                        .WithOne("Gestor")
                        .HasForeignKey("EFCore.WebAPI.Dominio.Gestor", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
